[package]
name = "sapota"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sapota"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
serde_json = "1.0.133"
